version: '3.8'
services:
  wwww:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
  db: 
    image: mysql:latest
    enviroment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPT_PASSWORD 