version: '3.8'
services:
  wwww:
    image: php:apache
    volumes:
      - "./src:/var/www/html"
    ports:
      - '80:80'
    environment:
  db: 
    image: mysql:latest
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE: dbtest
      - MYSQL_USER: superman
      - MYSQL_PASSWORD: test
      - MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      -'3306:3306'