version: "4"
services:
  web:
    image: php:apache
    volumes:
      - ./proyecto:/var/www/html
    ports:
      - 80:80
  db: 
    image: mysql:latest
    volumes:
      - ./proyecto/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbtest
      MYSQL_USER: superman
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"