version: "3.8"
services:
  web:
    build: .
    volumes:
      - ./proyecto:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
    ports:
      - 80:80
  db: 
    image: mysql:8.0
    volumes:
      - ./proyecto/db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=passwd
    - MYSQL_DATABASE=sigto
    expose:
      - "3306"
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306