version: '3.8'
services:
  wwww:
    image: php:apachea
    volumes:
      - "./src:/var/www/html"
    ports:
      - '80:80'
    environment:
  db: 
    image: mysql:latest
    volumes:
      - ./database:/var/lib/mysql
    enviroment:
      - MYSQL_DATABASE:
      - MYSQL_USER:
      - MYSQL_PASSWORD:
      - MYSQL_ALLOW_EMPTY_PASSWORD: 
    ports:
      -'3306:3306'