---
- hosts: all
  tasks:
    - name: Cambiar puerto de default de ssh
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#Port\ 22'
        line: Port 5645

    - name: Desactivar ingreso como root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin\ yes'
        line: PermitRootLogin no

    - name: Desactivar autenticacion por password
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication\ yes'
        line: PasswordAuthentication no

    - name: Acceso a usuarios definidos en ssh config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: AllowUsers sysadmin
        create: yes

    - name: Reiniciar ssh
      systemd:
        state: restarted
        name: sshd
        enabled: yes