---
- hosts: all
  - name: Crear usuario sysadmin
    user:
      name: sysadmin
      password : "{{ 'superpassword' | password_hash('sha512', 'supersecretohasheo') }}"
      create_home: false
      groups:
        - wheel
        - administrativo
  
  - name: Registrar clave pública del usuario
      authorized_key:
        user: sysadmin
        state: present
        key: "{{ lookup('file', '/Users/estebanmartinez/.ssh/id_rsa.pub') }}"
        
